FROM openjdk:8-jre-alpine

MAINTAINER Iduoad

WORKDIR /app

COPY target/microservice-notification-0.0.1-SNAPSHOT.jar /app/

ENTRYPOINT ["java", "-jar", "microservice-notification-0.0.1-SNAPSHOT.jar"]
